#!/bin/bash
termux-setup-storage
apt upgrade
apt update 
pkg upgrade
pkg update
pkg update && pkg upgrade
pkg install python
qemu-system-i386 -y
pkg install x11-repo -y
pkg install qemu-user-i386 -y
pkg install python git clang
pip install --upgrade pip
pkg upgrade
apt update && apt upgrade -y
apt install python
apt install python3
apt install git
apt install wget
apt install qemu-user-i386
pkg install ruby
gem install lolcat
pkg install figlet
pip install pyyaml
pkg update && pkg upgrade

pip install pyyaml

pkg install python-pip
pkg install python-pip
pip install tqdm